# TODO
# - In Gitlab: You'll need to create two variables in Project > Variables:
#   HEROKU_STAGING_API_KEY - Heroku API key used to deploy staging app,
#   HEROKU_PRODUCTION_API_KEY - Heroku API key used to deploy production app.

test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
#  - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
#  - apt-get update -qy
#  - apt-get install -y python-dev python-pip
#  - pip install -r requirements.txt
#  - python manage.py test

staging:
  type: deploy
  script:
#  - apt-get update -qy
#  - apt-get install -y ruby-dev
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-python-test-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  type: deploy
  script:
#  - apt-get update -qy
#  - apt-get install -y ruby-dev
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-python-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags